fix: github actions now has the correct files

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,6 +28,11 @@ jobs:
       - name: Build with Maven
         run: mvn clean package -DskipTests --file pom.xml
 
+      - name: Inspect JAR contents
+        run: |
+         jar tf target/sweetshop-0.0.1-SNAPSHOT.jar | grep postgresql || echo "PostgreSQL driver not found!"
+
+
       - name: Verify JAR built
         run: ls -lh target
 
